title: base
extends@:
  type: default

form:
  fields:
    tabs:
      fields:
        content:
          fields:
            # content:
            #   unset@: true
            header.media_order:
              ordering@: 99

        hero:
          type: tab
          title: THEME_C.HERO.IMAGE
          ordering@: -2
          fields:
            #
            # Custom way to use hero images
            # All available hero images get stored in /_heros and you can select from a them
            #

            header.hero.image:
              type: pagemediaselect
              label: THEME_C.HERO.IMAGE
              # folder: 'page://_heros'
              preview_images: true
              accept:
                - .jpg
                - .jpeg

            header.hero.headline:
              type: text
              label: THEME_C.HERO.HEADLINE
              toggleable: true

            header.hero.author:
              type: text
              label: THEME_C.HERO.SOURCE
              toggleable: true

        advanced:
          fields:
            overrides:
              security: admin.super
              header.hide_breadcrumbs:
                type: toggle
                label: THEME_C.PAGE.BREADCRUMB
                toggleable: true
                default: 0
                highlight: 0
                options:
                    0: THEME_C.PAGE.SHOW
                    1: THEME_C.PAGE.HIDE
                validate:
                    type: bool
            routes_only:
              security: admin.super
            admin_only:
              security: admin.super