extends@: default

form:
  fields:
    tabs:
      active: 1
      fields:
        content:
          fields:
            content:
              type: ignore
              # unset@: true
            header.test:
              ordering@: -1
              name: module_slideshow
              title: TEST
              type: fieldset
              icon: picture-o
              fields:
                header.test.columns:
                  type: columns
                  fields:
                    column1:
                      type: column
                      fields:
                        header.test.animation:
                          name: slideshow_animation
                          label: TEST.ANIMATION
                          type: select
                          options:
                            slide: 'slide'
                            fade: 'fade'
                        header.test.speed:
                          name: slideshow_speed
                          label: TEST.SPEED
                          type: text
                          size: small
                        header.test.settings:
                          type: fieldset
                          name: test_settings
                          title: NESTED TEST
                          icon: wrench
                          collapsible: true
                          collapsed: true
                          fields:
                            header.test.settings.content_transition:
                              name: slideshow_slides_content_transition
                              label: TEST.SETTINGS.CONTENT.TRANSITION
                              type: select
                              options:
                                fade: 'transition-fade'
                                slide-top: 'transition-slide-top'
                    column2:
                      type: column
                      fields:
                        .header.test.content:
                          name: slideshow_slides_content_overlay
                          label: TEST.CONTENT.PARALLAX
                          type: text
                        .header.test.list:
                          type: list
                          name: module_slideshow
                          label: TEST.LIST
                          icon: slideshows
                          collapsed: false
                          collapsible: false
                          fields:
                            .header.test.list.pauseonhover:
                              name: test_pauseonhover
                              label: TEST.LIST.PAUSEONHOVER
                              type: toggle
                              default: 1
                              options:
                                0: GENERAL.NO
                                1: GENERAL.YES
                              validate:
                                type: bool