title: base
'@extends':
  type: default

form:
  fields:
    tabs:
      fields:
        content:
          fields:
            # content:
            #   unset@: true
            header.media_order:
              ordering@: 99
        advanced:
          fields:
            overrides:
              security: admin.super
            routes_only:
              security: admin.super
            admin_only:
              security: admin.super